/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;

import java.util.regex.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author Dell
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    //String selectedPhoto;
    
    EmployeeHistory history;
    public CreateJPanel(EmployeeHistory history) {
        initComponents();
        this.history=history;
       
    
    
 
    }
    //boolean lblInvalidName;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmpId = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblCellPhoneNum = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmpId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtLevl = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtCellPhoneNum = new javax.swing.JTextField();
        txtEmailAdd = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnupload = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        txtimage = new javax.swing.JTextField();
        lblInvalidName = new javax.swing.JLabel();
        lblInvalidEmpId = new javax.swing.JLabel();
        lblInvalidEmailId = new javax.swing.JLabel();
        lblInvalidAge = new javax.swing.JLabel();
        lblInvalidGender = new javax.swing.JLabel();
        lblInvalidCellphonenum = new javax.swing.JLabel();
        lblInvalidStartdate = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("                             Human Resources Management System");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setText("Name");

        lblEmpId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpId.setText("Employee ID");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setText("Gender");

        lblLevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLevel.setText("Level");

        lblStartDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStartDate.setText("Start Date");

        lblTeamInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTeamInfo.setText("Team Info");

        lblPositionTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPositionTitle.setText("Position Title");

        lblCellPhoneNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCellPhoneNum.setText("Cell Phone Number");

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmailAddress.setText("Emial Address");

        txtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtEmpId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmpIdKeyReleased(evt);
            }
        });

        txtAge.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        txtGender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGenderKeyReleased(evt);
            }
        });

        txtStartDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStartDateKeyReleased(evt);
            }
        });

        txtLevl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTeamInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPositionTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionTitleActionPerformed(evt);
            }
        });

        txtCellPhoneNum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCellPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellPhoneNumActionPerformed(evt);
            }
        });
        txtCellPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCellPhoneNumKeyReleased(evt);
            }
        });

        txtEmailAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddActionPerformed(evt);
            }
        });
        txtEmailAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailAddKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnupload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupload.setText("Upload Photo");
        btnupload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });

        lblimage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblimage.setText("Image");

        txtimage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimageActionPerformed(evt);
            }
        });

        lblInvalidName.setForeground(new java.awt.Color(255, 0, 0));
        lblInvalidName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblInvalidNameKeyPressed(evt);
            }
        });

        lblInvalidEmpId.setForeground(new java.awt.Color(255, 0, 0));
        lblInvalidEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblInvalidEmpIdKeyPressed(evt);
            }
        });

        lblInvalidEmailId.setForeground(new java.awt.Color(255, 0, 0));
        lblInvalidEmailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblInvalidEmailIdKeyPressed(evt);
            }
        });

        lblInvalidAge.setForeground(new java.awt.Color(255, 0, 0));
        lblInvalidAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblInvalidAgeKeyPressed(evt);
            }
        });

        lblInvalidGender.setForeground(new java.awt.Color(255, 0, 0));
        lblInvalidGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblInvalidGenderKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblInvalidGenderKeyReleased(evt);
            }
        });

        lblInvalidCellphonenum.setForeground(new java.awt.Color(255, 0, 0));
        lblInvalidCellphonenum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblInvalidCellphonenumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblInvalidCellphonenumKeyReleased(evt);
            }
        });

        lblInvalidStartdate.setForeground(new java.awt.Color(255, 0, 0));
        lblInvalidStartdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblInvalidStartdateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblInvalidStartdateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addGap(307, 307, 307))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmpId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCellPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPositionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtimage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtCellPhoneNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPositionTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLevl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtEmailAdd, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInvalidCellphonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInvalidAge, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInvalidGender, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInvalidName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInvalidEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInvalidEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInvalidStartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(171, 171, 171)
                                        .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInvalidName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmpId)
                                .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInvalidEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGender)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInvalidAge, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInvalidGender, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInvalidStartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLevl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLevel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTeamInfo)
                                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPositionTitle)
                    .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCellPhoneNum)
                            .addComponent(txtCellPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailAddress)
                            .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInvalidCellphonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblInvalidEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblimage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionTitleActionPerformed

    private void txtCellPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCellPhoneNumActionPerformed

    private void txtEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        // TODO add your handling code here:

        
       String name =txtName.getText();
       String empid=txtEmpId.getText();
       String age=txtAge.getText();
        String gender=txtGender.getText();
        String startdate=txtStartDate.getText();
        String level=txtLevl.getText();
        String teaminfo=txtTeamInfo.getText();
        String positiontitle=txtPositionTitle.getText();
        String cellphonenum=txtCellPhoneNum.getText();
        String emailid=txtEmailAdd.getText();
        String selectedPhoto=txtimage.getText();
         // txtimage.setText(selectedemp.getPhoto());
         
         //if (name.equals(null)&&empid.equals(null)&&age.equals(null)&&gender.equals(null)&&startdate.equals(null)&&level.equals(null)&&teaminfo.equals(null)&&positiontitle.equals(null)&&cellphonenum.equals(null)&&emailid.equals(null)&&selectedPhoto.equals(null))      
         //        JOptionPane.showMessageDialog(null, "All Fields are Manidtory");
             
         
    
        
        Employee e = history.addNewemps();
        
       e.setName(name);
       e.setEmpid(empid);
       e.setAge(age);
       e.setGender(gender);
       e.setStartdate(startdate);
       e.setLevel(level);
       e.setTeaminfo(teaminfo);
       e.setPositiontitle(positiontitle);
       e.setCellphonenum(cellphonenum);
       e.setEmailid(emailid);
       e.setPhoto(selectedPhoto);
       
        JOptionPane.showMessageDialog(this, "New Employee added");
        
        txtName.setText("");
        txtEmpId.setText("");
        txtAge.setText("");
        txtGender.setText("");
        txtStartDate.setText("");
        txtLevl.setText("");
        txtTeamInfo.setText("");
        txtPositionTitle.setText("");
        txtCellPhoneNum.setText("");
        txtEmailAdd.setText("");
        txtimage.setText("");
        lblPhoto.setIcon(new ImageIcon());
        
        
       
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 supported extensions", "jpg","jpeg","gif","png");
         fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(null);
        
         if(selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String getSelectedImage = file.getAbsolutePath();
            JOptionPane.showMessageDialog(null, getSelectedImage);
            ImageIcon imIco = new ImageIcon(getSelectedImage);
            
            txtimage.setText(file.getAbsolutePath());
           
           
            //image to fit in the jlabel
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
            lblPhoto.setIcon(new ImageIcon(imFit));
        }
    }//GEN-LAST:event_btnuploadActionPerformed

    private void txtimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimageActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
             String PATTERN="^[a-zA-Z\\s]+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtName.getText());
        if(!match.matches()){
            lblInvalidName.setText("Entered name is Invalid");
        }
         else{
               lblInvalidName.setText(null);  
        }
                     
       
              // TODO add your handling code here:
                     
    }//GEN-LAST:event_txtNameKeyReleased

    private void lblInvalidNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidNameKeyPressed
        // TODO add your handling code here:
        
           // TODO add your handling code here:
        
    }//GEN-LAST:event_lblInvalidNameKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed

//        String PATTERN="^[a-zA-Z\\s]+";
//        Pattern patt=Pattern.compile(PATTERN);
//        Matcher match=patt.matcher(txtName.getText());
//        if(!match.matches()){
//            lblInvalidName.setText("Entered name is Invalid");
//        }
//        else{
//               lblInvalidName.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed
    
    private void txtEmpIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpIdKeyReleased
//        // TODO add your handling code here:
       String PATTERN="[+-]?[0-9]+";
      Pattern patt=Pattern.compile(PATTERN);
       Matcher match=patt.matcher(txtEmpId.getText());   
       if(!match.matches()){          
           lblInvalidEmpId.setText("Entered Employee Id is Invalid");
       }
        else{
              lblInvalidEmpId.setText(null);        // TODO add your handling code here:
   
                    }// TODO add your handling code here:   }  
    }//GEN-LAST:event_txtEmpIdKeyReleased

    private void txtEmpIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpIdKeyPressed
                
    }//GEN-LAST:event_txtEmpIdKeyPressed

    private void lblInvalidEmpIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidEmpIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidEmpIdKeyPressed

    private void lblInvalidEmailIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidEmailIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidEmailIdKeyPressed

    private void txtEmailAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddKeyPressed
        // TODO add your handling code here:
                          
    }//GEN-LAST:event_txtEmailAddKeyPressed

    private void txtEmailAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddKeyReleased
        // TODO add your handling code here:
         //String PATTERN="^(.+)@(.+)$";
         String PATTERN="(?:^|\\s)[\\w!#$%&'*+/=?^`{|}~-](\\.?[\\w!#$%&'*+/=?^`{|}~-]+)*@\\w+[.-]?\\w*\\.[a-zA-Z]{2,3}\\b";
      Pattern patt=Pattern.compile(PATTERN);
       Matcher match=patt.matcher(txtEmailAdd.getText());   
       if(!match.matches()){          
           lblInvalidEmailId.setText("Entered email Id is Invalid");
       }
        else{
              lblInvalidEmailId.setText(null);        // TODO add your handling code here:
  }            
    }//GEN-LAST:event_txtEmailAddKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
         String PATTERN="^(?:(?!0)\\d{1,2}|100)$";
      Pattern patt=Pattern.compile(PATTERN);
       Matcher match=patt.matcher(txtAge.getText());   
       if(!match.matches()){          
           lblInvalidAge.setText("Entered value is Invalid");
       }
        else{
              lblInvalidAge.setText(null);        // TODO add your handling code here:
  }           
    }//GEN-LAST:event_txtAgeKeyReleased

    private void lblInvalidAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidAgeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidAgeKeyPressed

    private void lblInvalidGenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidGenderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidGenderKeyPressed

    private void lblInvalidGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidGenderKeyReleased
        // TODO add your handling code here:
 
    }//GEN-LAST:event_lblInvalidGenderKeyReleased

    private void txtGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyReleased
        // TODO add your handling code here:
             String PATTERN="^M(ale)?$|^F(emale)?$";
      Pattern patt=Pattern.compile(PATTERN);
       Matcher match=patt.matcher(txtGender.getText());   
       if(!match.matches()){          
           lblInvalidGender.setText("Male/Female");
       }
        else{
              lblInvalidGender.setText(null);        // TODO add your handling code here:
  }      
      
    }//GEN-LAST:event_txtGenderKeyReleased

    private void lblInvalidCellphonenumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidCellphonenumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidCellphonenumKeyPressed

    private void lblInvalidCellphonenumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidCellphonenumKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidCellphonenumKeyReleased

    private void txtCellPhoneNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCellPhoneNumKeyReleased
        // TODO add your handling code here:
         String PATTERN="^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$";
      Pattern patt=Pattern.compile(PATTERN);
       Matcher match=patt.matcher(txtCellPhoneNum.getText());   
       if(!match.matches()){          
           lblInvalidCellphonenum.setText("Invalid CellPhone Number");
       }
        else{
              lblInvalidCellphonenum.setText(null);        // TODO add your handling code here:
  }      
    }//GEN-LAST:event_txtCellPhoneNumKeyReleased

    private void lblInvalidStartdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidStartdateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidStartdateKeyPressed

    private void lblInvalidStartdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInvalidStartdateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvalidStartdateKeyReleased

    private void txtStartDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartDateKeyReleased
        // TODO add your handling code here:
//        Date of birth: 1900/12/01
//
//           Date of birth: 2019.01.25
//
//            Birthday: 2099-10-30
        String PATTERN="^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$";
      Pattern patt=Pattern.compile(PATTERN);
       Matcher match=patt.matcher(txtStartDate.getText());   
       if(!match.matches()){          
           lblInvalidStartdate.setText("Invalid Date entered");
       }
        else{
              lblInvalidStartdate.setText(null);        // TODO add your handling code here:
  }      
    }//GEN-LAST:event_txtStartDateKeyReleased
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnupload;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCellPhoneNum;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblInvalidAge;
    private javax.swing.JLabel lblInvalidCellphonenum;
    private javax.swing.JLabel lblInvalidEmailId;
    private javax.swing.JLabel lblInvalidEmpId;
    private javax.swing.JLabel lblInvalidGender;
    private javax.swing.JLabel lblInvalidName;
    private javax.swing.JLabel lblInvalidStartdate;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCellPhoneNum;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevl;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    private javax.swing.JTextField txtimage;
    // End of variables declaration//GEN-END:variables
}
